version: '3.7'

services:
    nginx:
        # container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ${APPLICATION}:/var/www/html
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        env_file: .env
        ports:
            - "${ADDRESS_PROXY_01_PORT}:8081"
            - "${ADDRESS_PROXY_02_PORT}:8082"
            - "${ADDRESS_PROXY_03_PORT}:8083"
            - "${ADDRESS_PROXY_04_PORT}:8084"
            - "${ADDRESS_PROXY_05_PORT}:8085"
